version: '3.8'

services:
  label-studio-ml-backend:
    build: .
    image: label-studio-ml-backend
    container_name: label-studio-ml-backend
    ports:
      - "9090:9090"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      # AWS Rekognition Configuration
      - REKOGNITION_PROJECT_ARN=arn:aws:rekognition:us-east-1:030179562632:project/sdi-object-detector/version/sdi-object-detector.2025-12-11T19.13.51/1765502031650
      - MIN_CONFIDENCE=50
      # Flask Configuration
      - PORT=9090
      - LOG_LEVEL=INFO
    volumes:
      # copy-pastes your AWS credentials file and then keeps it in sync
      - ~/.aws:/root/.aws:ro
